version: '3.9'
services:
  my-app: 
    image: my-app:1.2
    ports:
     - 3000:3000
    environment:
     - MONGO_DB_USERNAME=admin123
     - MONGO_DB_PASSWORD=password123
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin123
     - MONGO_INITDB_ROOT_PASSWORD=password123
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin123
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
     - ME_CONFIG_MONGODB_SERVER=mongodb       
      